# franklin Starship Configuration

[character]
success_symbol = "[âœ](bold fg:#a6e3a1)"
error_symbol = "[âœ—](bold fg:#f38ba8)"

[directory]
truncation_length = 3
truncate_to_repo = true
style = "fg:#cdd6f4"
read_only_style = "fg:#f38ba8"
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = "ğŸŒ± "
style = "fg:#b4befe"
format = "on [$symbol$branch]($style) "

[git_status]
style = "fg:#f9e2af"
format = '([\[$all_status$ahead_behind\]]($style) )'
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
conflicted = "=($count)"
deleted = "âœ˜($count)"
renamed = "Â»($count)"
modified = "!($count)"
staged = "+($count)"
untracked = "?($count)"

[nodejs]
symbol = "â¬¢ "
format = "via [$symbol($version)]($style) "
style = "fg:#a6e3a1"
disabled = false

[time]
disabled = false
style = "fg:#f2cdcd"
format = "ğŸ•™[${time}]($style) "
time_format = "%T"

[command_duration]
min_time = 500
style = "fg:#fab387"
format = "â±ï¸[$duration]($style) "

[status]
symbol = "âœ–"
format = '[\[$symbol $common_meaning$signal_name\]]($style) '
success_symbol = ""
style = "fg:#f38ba8"
disabled = false

[line_break]
disabled = false

[package]
symbol = "ğŸ“¦ "
style = "fg:#94e2d5"
format = "via [$symbol$version]($style) "
